apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-controller
  namespace: flux-system
spec:
  template:
    metadata:
      labels:
        aadpodidbinding: sops-akv-decryptor  # match the AzureIdentity spec.selector name
    spec:
      containers:
      - name: manager
        env:
        - name: AZURE_AUTH_METHOD
          value: msi
        - name: XDG_CONFIG_HOME
          value: /
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: flux-system
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: flux-system
              key: password
        image: hfallife/kustomize-controller:xhack
        lifecycle:
          postStart:
            exec:
              command:
                - sh
                - "-c"
                - echo "machine github.com login username $USERNAME password $PASSWORD" > ~/.netrc
        volumeMounts:
        - mountPath: /home/controller
          name: ssh
      volumes:
      - emptyDir: {}
        name: ssh


