---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: admin
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 5s
  path: ./config/k8s/application/upm-api-admin
  prune: true
  sourceRef:
    kind: GitRepository
    name: substrate
  validation: client

