---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: substrate
  namespace: flux-system
spec:
  interval: 3s
  ref:
    branch: flux-test-1
  secretRef:
    name: flux-auth
  url: https://github.com/EnterpriseDB/upm-substrate.git

